site_name: andrew_test
site_description: Testing cookiecutter

repo_url: https://github.com/dinbergare/andrew_test
repo_name: dinbergare/andrew_test

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: red
          accent: red
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.12/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - andrew_test

nav:
    - About: index.md
    - Testing: testing.md
    - Reference:
        - andrew_test: reference/andrew_test.md
